---
apiVersion: v1
kind: Service
metadata:
    name: travis-gradle
    namespace: travis-gradle
    labels:
      owner: fruetalo182
      repo: travis-gradle
spec:
  selector:
    app: travis-gradle
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP