---
apiVersion: v1
kind: Service
metadata:
    name: maven-hoppus
    namespace: maven-hoppus
    labels:
      owner: fruetalo182
      repo: "https://github.com/fruetalo182/maven-hoppus"
spec:
  selector:
    app: maven-hoppus
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP