apiVersion: apps/v1
kind: Deployment
metadata:
    name: tom-de-go
    namespace: tom-de-go
    labels:
      owner: fruetalo182
      repo: tom-de-go
spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: tom-de-go
    template:
      metadata:
        labels:
          app: tom-de-go
          owner: fruetalo182
          repo: tom-de-go"
      spec:
        containers:
          - name: tom-de-go
            image: ghcr.io/fruetalo182/tom-de-go:latest
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: "200m"
                memory: "200Mi"
              limits:
                cpu: "400m"
                memory: "400Mi"
            ports:
            - name: http
              containerPort: 8080
            envFrom:
            - secretRef:
                name: tom-de-go
                optional: true
