---
apiVersion: v1
kind: Service
metadata:
    name: tom-de-go
    namespace: tom-de-go
    labels:
      owner: fruetalo182
      repo: tom-de-go
spec:
  selector:
    app: tom-de-go
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP