apiVersion: v1
kind: Service
metadata:
  name: canary-demo-preview
  namespace: rollout-canary-experiment
spec:
  selector:
    app: canary-demo
  ports:
  - name: http
    port: 80
    targetPort: 8080
